services:
  - type: web
    name: demo-repository
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    plan: free
    autoDeploy: true
    healthCheckPath: /
